/**
 * Publish a kind 30406 shipping option. Reusable per-seller asset
 * referenced from listings via `["shipping_option", "30406:pubkey:dtag"]`.
 *
 * Flow mirrors publishProduct.js but stripped of the relay-override
 * complexity: shipping options are profile-level catalog entries, not
 * promotional posts, so they always go to the seller's own outbox.
 *
 * d-tags MUST be stable across renames — listings reference options by
 * coord, and changing the d-tag silently breaks every listing that
 * already linked to it. UUID-style identifiers are generated by the
 * caller (useShippingOptions hook); this helper just signs and ships.
 */
import { CLIENT_TAG } from './brand.js'
import { NDKEvent } from '@nostr-dev-kit/ndk'
import { nip19 } from 'nostr-tools'
import { getNDK, signWithTimeout, publishToOwnOutbox, FALLBACK_RELAYS } from './ndk.js'
import { encodeShippingOption, KIND_SHIPPING_OPTION } from './gamma.js'

/**
 * @param {object} form — gamma.encodeShippingOption-shaped form. Required
 *   fields: dTag, title. Recommended: price, countries, service.
 * @returns {Promise<{naddr: string, eventId: string, relays: string[], event: NDKEvent}>}
 *   `event` is the signed NDKEvent — caller can pass it straight to
 *   local-state hooks instead of re-fetching to learn `created_at`.
 */
export async function publishShippingOption(form) {
  const ndk = getNDK()
  const { kind, content, tags } = encodeShippingOption(form)

  // Stamp `client` so other clients can attribute. Mirrors publishProduct.
  // Filter out a foreign 'client' tag if it survived from _extraTags so
  // a cross-client edit doesn't accumulate duplicates.
  const finalTags = tags
    .filter(t => t[0] !== 'client')
    .concat([['client', CLIENT_TAG]])

  const event = new NDKEvent(ndk)
  event.kind = kind
  event.content = content
  event.created_at = Math.floor(Date.now() / 1000)
  event.tags = finalTags

  // Outbox-aware publish: replaceable kind (30406) needs to land on the
  // user's own write relays so future edits/deletes target the same set.
  let hintRelays = FALLBACK_RELAYS
  try {
    const relayList = await ndk.activeUser?.relayList()
    const writeRelays = relayList?.writeRelayUrls
    if (writeRelays?.length) hintRelays = writeRelays
  } catch {}

  await signWithTimeout(event)
  const publishedTo = await publishToOwnOutbox(event)
  const confirmedRelays = Array.from(publishedTo).map(r => r.url).filter(Boolean)
  const relays = confirmedRelays.length ? confirmedRelays : hintRelays

  const naddr = nip19.naddrEncode({
    kind: KIND_SHIPPING_OPTION,
    pubkey: event.pubkey,
    identifier: form.dTag,
    relays: relays.slice(0, 3),
  })

  return { naddr, eventId: event.id, relays, event }
}
